version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  node:
    image: node:14
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    working_dir: /app

volumes:
  mysql-data: